[WIP] Tests
natalia-sk/test_DRF_project pull request #11
Opened 2021-09-09 12:26 UTC by natalia-sk

2021-09-15 08:33 UTC, volgoweb approved these changes

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/factories.py
> +    content = Faker("paragraph")
looks awesome

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/test_article_model.py
> +        ):
have you run the tests? Based on my experience the code without `re.escape` will work properly.

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/test_article_model.py
> +def test_article_model_raises_exception():
The name of test function should explain what is tested.
In this case, I would name the function `test_article_title_length_constraint` or `test_max_length_of_article_title_is_150`.

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/test_article_model.py
> +        Article.objects.create(title="test" * 150, content="test content")
If the test checks a limit then the next possible value should be used. In this case, `title="s"*151 `

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/test_article_serializer.py
> +    assert set(serializer_fields.keys()) == set(['id', 'title', 'content'])
An empty line between logical blocks (in this code it is `# GIVEN`, `# WHEN`, `# THEN`) increases readability.

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/test_article_serializer.py
> +def test_serializer_contains_expected_fields():
Good coverage of serializers should contain comprehensive checking of serialized data.
Or tests of the view may cover everything (checking keys, checking a response content at all).

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/test_article_view.py
> +    request = client.get('/articles/articles/1')
A  good practice is to use `django.urls.reverse` to build a path from the view name and kwargs.

2021-09-15 08:33 UTC, volgoweb commented on study_time/articles/tests/test_article_view.py
> +    assert request.status_code == 403
the constants (`rest_framework.status.HTTP_*`) is more preferable

2021-09-15 08:33 UTC, volgoweb commented on study_time/tests/factories.py
> +    password = "test_password"
Most likely, this code can be omitted and nothing happens.

2021-09-20 17:32 UTC, volgoweb requested changes
I really like your code. 
Please take a look at my recommendations.

2021-09-20 17:32 UTC, volgoweb commented on study_time/articles/tests/test_article_view.py
> +    assert Article.objects.get().content == response.json()["content"]
1. I'm not 100% sure but it's really possible that every `Article.objects.get().` produces a query to the database. The code should strive to send as low count of queries to DB as possible.
2. Also, `article` looks shortly and more readable than `Article.objects.get()`.
3. `.json()` can and should be called one time only. After that using a variable is preferable. Shortly and faster.
3. A comparison of whole dictionary (`response_data == {"some expected": "fields"}` provides a comprehensive checking with similar efforts.

2021-09-20 17:32 UTC, volgoweb commented on study_time/articles/tests/test_article_view.py
> +    response = client.delete(path=reverse("articles-detail", kwargs={"pk": article.id}))
the code of building a path is repeated. That's why it can be moved to the function like `get_article_detail_view_path(article_id)`.
If you will use a fixture then you will able to use a same article id (as a constant like `ARTICLE_ID`) everywhere. This will allow to use a path as a constants: `ARTICLE_DETAIL_PATH = reverse("articles-detail", kwargs={"pk": ARTICLE_ID})`

2021-09-20 17:32 UTC, volgoweb commented on study_time/articles/tests/test_article_view.py
> +    assert len(response.json()["results"]) == 3
Checking the list of dictionaries in "results" is needed because this is not covered in the tests of the serializer.
And this checking is not an attempt to cover `rest_framework` by tests because the serializer is a your own class that can contain some specific code that can modify serializing of any field totally.

2021-09-27 14:29 UTC, jakubramatowski reviewed
There are some things to iron out, but overall a great progress :+1:

2021-09-27 14:29 UTC, jakubramatowski commented on study_time/articles/tests/values.py
> +        ]
```suggestion
    "results": [
        {"id": article_id, "title": ARTICLE_TITLE, "content": ARTICLE_CONTENT} for article_id in ARTICLES_IDS
        ]
```

2021-09-27 14:29 UTC, jakubramatowski commented on study_time/articles/tests/test_article_view.py
> +    }
those could be moved to values as well

2021-09-27 14:29 UTC, jakubramatowski commented on study_time/articles/tests/test_article_view.py
> +    assert response_data == expected_changed_data
Try mapping response based on provided values, not values from model. If values stayed the same this test would pass as well

2021-09-27 14:29 UTC, jakubramatowski commented on study_time/articles/tests/test_article_view.py
> +        "content": "test article content"
those could be moved to values

2021-09-27 14:29 UTC, jakubramatowski commented on study_time/articles/tests/test_article_view.py
> +    request = client.get(reverse("articles-list"))
`ARTICLE_LIST_URL = reverse("articles-list")` in values would reduce amount of times that reduce is called

2021-09-27 14:29 UTC, jakubramatowski commented on study_time/articles/tests/test_article_view.py
> +    request = client.get(reverse("articles-detail", kwargs={"pk": values.ARTICLE_ID}))
since ARTICLE_ID is constant, you  can move it to values.py, same as list url

2021-09-27 14:29 UTC, jakubramatowski commented on study_time/articles/tests/test_article_view.py
> +    assert request.data == {"id": article.id, "title": article.title, "content": article.content}
test_article_detail makes more sense in this case, since this is a happy path.

2021-09-28 11:32 UTC, jakubramatowski approved these changes

2021-09-29 10:40 UTC, volgoweb approved these changes

2021-09-29 10:49 UTC, merged